os_auth_url         = "https://identity.spo1.edge.embratel.cloud:5000/v3"
os_username         = "Username1"
os_password         = "Password"
os_tenant_name      = "xxxxxxx-project"
os_domain           = "xxxxxxx-domain"
os_region           = "spo1"
